language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: Ncbj9xVyqtzWWbcnq6BnnYUTP5kypPQrB/AbM7knXMCLCtUiga0IR/yNvUSJGPpNCDa0pK1bxTN/P5i6XdxIO7NzS6/E+u18q+l+RyawrHlMQBlUnxQKSLB1EDNgovOHwglIUElkhrEk302f65wO8tzBp2+OxTW8VMhk+jrOYAJL4whxCgA8OGxgrT4AOj9jOlcXHvgCGT3l08oKTi73FAxDhljgPUdICFNRBie64VxaHrJYj3zGLUf56ViYjD2S2DJOtMoEeOuPbTb10gDuG5JDHj0ZBU5M+QyG8Vxx2F+vHESO+yEjjZdOLVNeKQVE1oMilakcS3jtVhDppqNw+xxlDKepXbWKaj8bF10ahv3jFCT20uA8pW/3LS3XsjbhnUw7NcSzQ3iEFNDDgwJVHlzatTNg6O3ZmMf4S2Gx56KrkITWC4L0nFPKSi216ixhgi21F4RrizaLHC8lPKXhFx6AGNRWiBfIQuSACyuDVo3GsiviEgTlUFm87395Z+5GJ9XB5p12bCHltEok5vaiHMDRQK2Epe6gSDuG3xgWJiGip22MFOyhXdX1GWXlPkggC4vhQkBUW5xMyL7284t3bGIiagV1ioU4XnLp+NHecGGt7q2NGCSUY+deGj1JBQuPfP3kjYu6P1t+t5hpzgu1KzFSCGqwO3PCMTlEH5iA/qM=
  on:
    tags: false
    repo: Mangopay/mangopay2-nodejs-sdk
    branch: release
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi