language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: mickael@mangopay.com
  api_key:
    secure: Xwq0xcp0PFcU8xEJgzX96Nh6xKEIRa7668bKVf7rH/6zaHcF1FgM0dfLYurQYa3edVyKF3x+QekHX6lXy1KuBccGlMZT/cXXHVBoXUjgZMt5zKB6PcetZZOQjv8kuqJ45o2DKDnVseKOV7zFG5MldbJ3ewXSz9Jap5LapxpuJ03W/WGY4AHXwMtsDURZsvseSLU4s1ODslzeRskrbn0kx2booF+dH0agIDylnKmGH81ni2DV1iB34U6adyws1NejWEuTX6Q2t39Vr8hjCdcd7D2FRky1JIdcCsVzlHhVx6vyteapW/8dEyXrJtsGC6BN/dQIdc9xFKbBakEMYZ3vrN/5j8E3zvSpmmd5rDBVQt5qjIgDig5YdfQisr+ve+pK0NwtZ1FFZjDOmIbbgW6b7vUHviQSF6HhrV5f2kzRVedUHmLVY34pykzHnFYxX12iuAaWJBRUPY8bCk1Zid+ha3PtyQ3+7KUeIqUy+WsI9xfh4G0Vuj42GNsibjoErdUVCOlp/M/DXws++cGY8SJ1Ih7CQv7oGpuLxuNSWpu9YDP/c7F6+IY2zRjU6IlX50uqA5sqWaMOpwirsBiLPfNy5ZgF9bQkWGaMI+bxKreP2ALTHcuHWrFbbF8GUPOPb1sbIPHUjUAHCexeTUnxdZdXL2iYnJzNdOCrJRvAZB+cWYo=
  on:
    tags: false
    repo: Mangopay/mangopay2-nodejs-sdk
    branch: release
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
env:
  global:
    secure: vFuUAomH7GQRDh+n5oGmXpnNkDFECX9O1t33c8pHey57AWhbhLNrJ+KJyx0f9lPIPZAVJqPRN/Biv+pGlCzne8vUUTM1PPz3936IhlWiRRPnsM4YpIMFMvt+Y/PkDmjoIWpiLeGyLfn3fqSLmKb8DBspVcW98sO3zglWIY8rXidlsCuNBVxZNh3fUU/qz8WrEj6UrNVPd1G2s8pvsw72KGN08OvyUAU9zk3G64e8vaE+7G+OTyUbpqfYYDqvEH+HrAeVI7nzSRUyZW9Bpz7e3mk7vya8tjfk6sHdcLxs7U6PBn8KxYrj83mQz0ByYk8wEi2oLYAfVkkvILNJ4mDdlvbwvNMcWQB8TKZemW31r7891Pwugnk3Qoqy4LPdRiy8R8dzpolU+l6vkxtzHhWKxG6LRwU/c9czdwn9cSvIdTcv4VXYr2jJkpOpkWhlOLMIF6XGFdUkANqUIW5yecCeKIbn+BA9I/kpKCZPk07RMaXAey3AMYMVEPabcXpUmrdSvDcHZrR/6dg9zyaWJ+JXZNfxCYDgQOXio3GKE3x+Xi6LEEKH4aXEGs5G2ZHOpFPem4croaPExYB64CXt2wTlPVjVazSbhKZUi+4RTW7N2ka+0GvqYp18D9HAfCVlilD3ONbjOIdSgpepmwGeUMTBpS6V6DYoLAEvvwFxpT8GD7o=
