language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: 'support@mangopay.com'
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: false
    repo: Mangopay/mangopay2-nodejs-sdk
    branch: release
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
